services:
  # Single web service serving both backend API and frontend static files
  - type: web
    name: hockey-stats-app
    runtime: python
    buildCommand: |
      cd backend && pip install -r requirements.txt &&
      cd ../frontend && npm ci && npm run build &&
      cp -r dist/* ../backend/static/
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"